import localFont from "next/font/local";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Suspense } from "react";
import { AuthProvider } from "./Providers";
import AuthLayout from "./AuthLayout"; // Import the AuthLayout component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Glimmer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Suspense>
          <AuthProvider>
            <AuthLayout>{children}</AuthLayout> 
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}