import * as React from "react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import "./globals.css";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "@/theme/defaultTheme";
import AppNavbar from "@/components/AppNavbar";
import ThemeNavbar from "@/components/ThemeNavbar";
import { Navbar } from "@nextui-org/react";

export const metadata = {
  title: "Glimmer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <CssBaseline enableColorScheme/>
            <AppNavbar />
            <main>{children}</main>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
